#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

exec 3>&1
exec 1>&2
payload="$(cat <&0)"

case "$0" in
    ('/opt/resource/check')
        json="$(cat <<ENDLINE
[
    {
        "digest": "sha256:$(uuidgen | sha256sum | cut -d ' ' -f 1)"
    }
]
ENDLINE
)"
        ;;
    ('/opt/resource/in')
        printenv | sort > "$1"/get-step.env
        if [ "$(jq -r '.version | has("digest") // false' <<< "$payload")" = 'true' ]; then
            json="$(cat <<ENDLINE
{
    "version": {
        "digest": "$(jq -r '.version.digest' <<< "$payload")"
    }
}
ENDLINE
)"
        else
            json="{}"
        fi
        ;;
    ('/opt/resource/out')
        json="$(cat <<ENDLINE
{
    "version": {
        "digest": "sha256:$(uuidgen | sha256sum | cut -d ' ' -f 1)"
    }
}
ENDLINE
)"
esac

echo "$json" >&3
