#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

exec 3>&1
exec 1>&2
jq -M -S . < /dev/stdin > /tmp/input.json

case "$0" in
    ('/opt/resource/check')
        json="$(cat <<ENDLINE
[
    {
        "digest": "sha256:$(uuidgen | sha256sum | cut -d ' ' -f 1)"
    }
]
ENDLINE
)"
        ;;
    ('/opt/resource/in')
        if [ "$(jq -r '.version | has("digest") // false' < /tmp/input.json)" = 'true' ]; then
            json="$(cat <<ENDLINE
{
    "version": {
        "digest": "$(jq -r '.version.digest' < /tmp/input.json)"
    }
}
ENDLINE
)"
        else
            json="{}"
        fi
        ;;
    ('/opt/resource/out')
        json="$(cat <<ENDLINE
{
    "version": {
        "digest": "sha256:$(uuidgen | sha256sum | cut -d ' ' -f 1)"
    }
}
ENDLINE
)"
esac

echo "$json" >&3
